---
- name: Install and Configure Bareos Client
  hosts: bareos-client
  become: true
  roles:
    - bareos-client

- name: Install and Configure Bareos Server
  hosts: bareos-server
  become: true
  roles:
    - bareos-server
    - bareos-jobs

- name: Restart Bareos FD on bareos-client group
  become: true
  hosts: bareos-client
  tasks:
    - name: Restart Bareos FD on the client
      ansible.builtin.systemd:
        name: bareos-fd
        state: restarted
