---
- name: Reload Apache
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Restart Bareos Director
  ansible.builtin.service:
    name: bareos-dir
    state: restarted

- name: Restart Bareos Storage Daemon
  ansible.builtin.service:
    name: bareos-sd
    state: restarted

- name: Restart Bareos File Daemon
  ansible.builtin.service:
    name: bareos-fd
    state: restarted
